title: Neil Guertin
# tagline: 
# description: 
baseurl: "/neilguertin-com" # Set to "/neilguertin-com" when using GitHub Pages default url (https://neilguertin.github.io/neilguertin-com/). Set to "" when using custom domain name (https://www.neilguertin.com/). When baseurl is set, run locally with `bundle exec jekyll serve --livereload --baseurl=""`
url: "https://www.neilguertin.com"

# tagline:
# email:
# description:
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
# logo:

compress_html:
  blanklines: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - assets/images/reading_original_covers
